datasets:
  - type: BlenderDataset
    base_dir: "data/nerf_synthetic/lego"
    split: "train"
  - type: BlenderDataset
    base_dir: "data/nerf_synthetic/lego"
    split: "val"
  - type: BlenderDataset
    base_dir: "data/nerf_synthetic/lego"
    split: "test"

runner:
  output_dir: results/nerf/lego
  debug: False
  print_per_iter: 100
  val_per_iter: 20000
  save_per_iter: 10000
  init_lr: 5.0e-4
  weight_decay: 0.0
  # lr warmup
  warmup_steps: 100
  warmup_lr: 1.0e-5
  linear_scale: True
  # lr decay
  lr_decay_type: exponential # cosine, exponential
  min_lr: 5.0e-5
   # 0.99..99: num_decimal_epoch * num_decimal_rate = 1, rate ** num_epoch ~= 0.36
   # 0.99..95: num_decimal_epoch * num_decimal_rate = 0.1, rate ** num_epoch ~= 0.60
  lr_decay_rate: 0.1
  lr_decay_iter_interval: 250000
  num_iters: 200000
  batch_size_list:
    - 1
    - 1
    - 1
  num_workers_list:
    - 16
    - 16
    - 16


pipeline:
  type: NeRFPipeline
  chunk_size_grid: 131072
  num_passes: 2
  output_rasterized_mc: true
  loss_weights:
    loss_prev_stage_rgb_mse: 1.0
    loss_rgb_mse: 1.0
  model:
    type: NeRFMLP
    color_dim: 3
    harmonic_functions_dir_append_intput: true
    harmonic_functions_xyz_append_intput: true
    input_dir: true
    input_skips:
    - 5
    input_xyz: true
    latent_dim: 0
    n_harmonic_functions_dir: 4
    n_harmonic_functions_xyz: 10
    n_hidden_neurons_dir: 128
    n_hidden_neurons_xyz: 256
    n_layers: 8
  ray_sampler:
    type: RaySampler
    image_height: 800
    image_width: 800
    max_depth: 6.0
    min_depth: 2.0
    n_pts_per_ray_evaluation: 64
    n_pts_per_ray_training: 64
    n_rays_per_image_sampled_from_mask: 4096
    scene_extent: 0.0
    stratified_point_sampling_training: true
    stratified_point_sampling_evaluation: false
  renderer:
    type: MultipassEmissionAbsorpsionRenderer
    append_coarse_samples_to_fine: true
    bg_color:
    - 0.0
    - 0.0
    - 0.0
    blend_output: true
    density_noise_std_train: 0.2
    n_pts_per_ray_fine_evaluation: 128
    n_pts_per_ray_fine_training: 128
